### ISSUE TITLE
Which reavtiveui version used for that project?

### ISSUE THREAD

**Issue by Jurabek** [mhorn69/ReactiveUI.Xamarin.Samples#1]

**Comment by mhorn69** [comment]
I used my own fork of ReactiveUI (5.99.5-beta) https://github.com/mhorn69/ReactiveUI/tree/with_android_2.1_support because I have made some unsynced changes.
But I do not recommend to use this sample since it is out of date but maybe you could get some ideas out of it.

**Comment by Jurabek** [comment]
No, I am not using it don't worry, I want use routing with Xamarin.Android I want just debug it but it's not running, I added last reactiveui libraries and there some compiler errors Could not found IRoutingParams interface.

**Comment by mhorn69** [comment]
You find the Interface here:

https://github.com/mhorn69/ReactiveUI/blob/with_android_2.1_support/ReactiveUI/RoutingState.cs

**Comment by Jurabek** [comment]
Thanks!
